# -*- coding: utf-8 -*-
"""Assignment_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-G_gTEKHhYQqdDU9LDND6O5esW4O0Srl
"""

# Task: Calculate Factorial Using Recursion


def factorial(n):

    if n == 0 or n == 1:
        return 1
    else:

        return n * factorial(n - 1)

# 2. Call the function with a sample number and print the result
sample_number = 5
result = factorial(sample_number)
print(f"The factorial of {sample_number} is: {result}")

import math

num = float(input("Enter a number: "))

# Calculate the square root, natural logarithm, and sine
sqrt_num = math.sqrt(num)
log_num = math.log(num)
sin_num = math.sin(num)

# Display the calculated results
print(f"Square root of {num}: {sqrt_num}")
print(f"Natural logarithm (base e) of {num}: {log_num}")
print(f"Sine of {num} (in radians): {sin_num}")